
# IMPORT MODULES

In [4]:
import pandas as pd
import numpy as np

# LOAD DATASET - simple variable

In [5]:
df = pd.read_csv("./test.csv")
df.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [6]:
X = df["x"].values.reshape(-1,1)
y = df["y"].values

# BUILD MODEL

In [7]:
import normal_equation_lr as linear_model
import imp
imp.reload(linear_model)

<module 'normal_equation_lr' from '/Users/sungchulchoi/workspace/ml_lab_assignment/normal_equation/theteamlab_io/submit/normal_equation_lr.py'>

In [8]:
lr = linear_model.LinearRegression(fit_intercept=True)

In [9]:
lr.fit(X, y)

In [10]:
lr.intercept

In [11]:
lr.coef

In [ ]:
lr.predict(X)[:10]

# VALIDATION

In [13]:
from sklearn import linear_model
sk_lr = linear_model.LinearRegression(normalize=False)
sk_lr.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
sk_lr.intercept_ 

-0.4618107736611776

In [ ]:
import numpy.testing as npt
npt.assert_almost_equal(sk_lr.intercept_, lr.intercept)

In [16]:
sk_lr.coef_

array([1.01433536])

In [17]:
sk_lr.coef_ 

array([1.01433536])

In [ ]:
np.isclose(lr.coef, sk_lr.coef_)

In [ ]:
lr.predict(X)[:10]

In [20]:
df_test = pd.read_csv("./train.csv")
df_test.head()

x          y
0  24  21.549452
1  50  47.464463
2  15  17.218656
3  38  36.586398
4  87  87.288984

In [21]:
X_test = df["x"].values.reshape(-1,1)

In [ ]:
lr.predict(X_test)[:5]

In [23]:
sk_lr.predict(X_test)[:5]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201])

# LOAD DATASET - multiple variables

In [24]:
df = pd.read_csv("./mlr09.csv")
df.head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  average_points_scored  
0                              0.672                    9.2  
1                              0.797                   11.7  
2                              0.761                   15.8  
3                              0.651                    8.6  
4                              0.900                   23.2

In [25]:
y = df["average_points_scored"].values

In [26]:
df.iloc[:,:-1].head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  
0                              0.672  
1                              0.797  
2                              0.761  
3                              0.651  
4                              0.900

In [27]:
X = df.iloc[:,:-1].values

In [28]:
X[:5]

array([[  6.8  , 225.   ,   0.442,   0.672],
       [  6.3  , 180.   ,   0.435,   0.797],
       [  6.4  , 190.   ,   0.456,   0.761],
       [  6.2  , 180.   ,   0.416,   0.651],
       [  6.9  , 205.   ,   0.449,   0.9  ]])

# RESCALED

In [29]:
mu_X = np.mean(X, axis=0)
std_X = np.std(X, axis=0)

rescaled_X = (X - mu_X) / std_X

In [30]:
rescaled_X[:5]

array([[ 0.46843663,  0.50336336, -0.12692668, -0.70404955],
       [-0.63137111, -0.99746237, -0.25187012,  0.55584824],
       [-0.41140956, -0.66394554,  0.12296022,  0.19299768],
       [-0.85133266, -0.99746237, -0.59100234, -0.91571238],
       [ 0.68839818, -0.1636703 , -0.00198323,  1.59400403]])

# VALIDATION

In [31]:
lr.fit(rescaled_X, y)

In [32]:
lr.coef

In [33]:
lr.intercept

In [34]:
sk_lr.fit(rescaled_X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [35]:
sk_lr.coef_

array([-1.67779283,  0.28359762,  2.68586629,  1.12816882])

In [36]:
sk_lr.intercept_

11.790740740740736