In [154]:
import sklearn
import numpy as np

In [155]:
from sklearn.datasets import load_iris
datasets = load_iris()

In [156]:
x_data = datasets["data"]
x_data[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [162]:
y_data = datasets["target"]
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [163]:
y_data = y_data.reshape([-1,1])
y_data[:3]

array([[0],
       [0],
       [0]])

In [164]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit(y_data)  
y_data = enc.transform(y_data).toarray()
y_data[-1]

array([ 0.,  0.,  1.])

In [174]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
x_data_minmax = min_max_scaler.fit_transform(x_data)
x_data_minmax[:3]

array([[ 0.22222222,  0.625     ,  0.06779661,  0.04166667],
       [ 0.16666667,  0.41666667,  0.06779661,  0.04166667],
       [ 0.11111111,  0.5       ,  0.05084746,  0.04166667]])

In [175]:
x_0 =np.ones(x_data_minmax.shape[0])
x_data_minmax = np.column_stack((x_0, x_data_minmax))

x_data_minmax[:3]

array([[ 1.        ,  0.22222222,  0.625     ,  0.06779661,  0.04166667],
       [ 1.        ,  0.16666667,  0.41666667,  0.06779661,  0.04166667],
       [ 1.        ,  0.11111111,  0.5       ,  0.05084746,  0.04166667]])

In [171]:
weights = np.random.uniform(size=(3,5))
weights

array([[ 0.77220898,  0.24301142,  0.40927827,  0.86382761,  0.62676598],
       [ 0.07258586,  0.49102064,  0.07903525,  0.71416394,  0.62421396],
       [ 0.3810097 ,  0.54390687,  0.69286096,  0.25485907,  0.89076409]])

In [187]:
def softmax(z):
    e = np.exp(z)
    p = e / np.sum(np.exp(z), axis=1).reshape([-1,1])
    return p

In [188]:
z = x_data_minmax.dot(weights.T)
z.shape

(150, 3)

In [191]:
softmax(z[:5])

array([[ 0.44245233,  0.18701108,  0.37053659],
       [ 0.44986115,  0.20089782,  0.34924103],
       [ 0.4505668 ,  0.19356279,  0.35587041],
       [ 0.45691096,  0.1966414 ,  0.34644764],
       [ 0.4435784 ,  0.18365526,  0.37276634]])

In [107]:
def cross_entropy_function(y, x, weights):
    z = x_data_minmax.dot(weights.T)
    result = - np.sum(
                np.sum(
                    (y * np.log(softmax(z))), axis=1).reshape((-1,1))
                )
    return result 

In [200]:
cross_entropy_function(y_data,x_data_minmax,weights)

173.4509439468851

In [201]:
def minimize_grdient(y, x, initial_weights, iterations = 500000, alpha=0.001):
    cost_history= []
    theta_history = []
    m = y.shape[0]
    theta = np.copy(initial_weights)
    
    number_of_classes = theta.shape[0]
    number_of_weights = theta.shape[1]
    
    for _ in range(iterations):
        original_theta = np.copy(theta)
        for k in range(number_of_classes):        
            for j in range(number_of_weights):
                partial_x = x[:, j]
                partial_entropy = y - softmax(x.dot(original_theta.T))
                theta[k][j]  = original_theta[k][j] + (
                    alpha* partial_entropy[:,k].dot(partial_x.T) ) /150
        if (_ % 10000) == 0:
            print(cross_entropy_function(y,x,theta)/150)
            cost_history.append(cross_entropy_function(y,x,theta))
    return theta, cost_history

            

In [144]:
# weights = minimize_grdient(y_data, x_data_minmax,weights)
theta, cost_history = minimize_grdient(y_data, x_data_minmax,weights)

1.24098409123
0.77225550124
0.621269905698
0.542115016127
0.491854735906
0.456018326393
0.428539782089
0.406424572511
0.388008673346
0.372283091704
0.358594329739
0.346496980158
0.335674943421
0.325896424472
0.316986789881
0.308811444852
0.301264617531
0.294261775365
0.287734355987
0.281626019213
0.27588992576
0.270486725384
0.265383045391
0.260550338582
0.255963993652
0.251602640091
0.247447599142
0.243482445803
0.239692656186
0.236065321186
0.232588912127
0.229253087545
0.226048532774
0.222966825895
0.220000325044
0.217142073113
0.214385716736
0.211725437057
0.209155890275
0.206672156361
0.204269694616
0.201944305013
0.199692094416
0.197509446977
0.19539299807
0.193339611288
0.191346358059
0.189410499537
0.18752947046
0.185700864719


In [202]:
rand_index= np.random.randint(0,150,30)
rand_index

array([ 67,  41, 137,  33,  86, 108,  27,  13,  48,  65,  73, 146, 149,
        75, 142, 108,  60,  83,  24,   4,  25,  48,  65, 106,  86,  80,
        95,   9, 137,  43])

In [208]:
y_pred = np.argmax(softmax(x_data_minmax[rand_index].dot(theta.T)),axis=1) 
y_pred

array([1, 0, 2, 0, 1, 2, 0, 0, 0, 1, 1, 2, 2, 1, 2, 2, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 2, 0])

In [211]:
y_true = np.argmax(y_data[rand_index],axis=1)
y_true

array([1, 0, 2, 0, 1, 2, 0, 0, 0, 1, 1, 2, 2, 1, 2, 2, 1, 1, 0, 0, 0, 0, 1,
       2, 1, 1, 1, 0, 2, 0])

In [212]:
y_pred == y_true

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True], dtype=bool)

In [213]:
sum(y_pred == y_true) / len(rand_index)

0.96666666666666667