### The Boston Housing Dataset
https://archive.ics.uci.edu/ml/datasets/Housing

In [1]:
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
import numpy as np

In [8]:
boston = load_boston()

In [2]:
x_data = boston.data
y_data = boston.target.reshape(boston.target.size,1)

x_data[:3]

array([[  6.32000000e-03,   1.80000000e+01,   2.31000000e+00,
          0.00000000e+00,   5.38000000e-01,   6.57500000e+00,
          6.52000000e+01,   4.09000000e+00,   1.00000000e+00,
          2.96000000e+02,   1.53000000e+01,   3.96900000e+02,
          4.98000000e+00],
       [  2.73100000e-02,   0.00000000e+00,   7.07000000e+00,
          0.00000000e+00,   4.69000000e-01,   6.42100000e+00,
          7.89000000e+01,   4.96710000e+00,   2.00000000e+00,
          2.42000000e+02,   1.78000000e+01,   3.96900000e+02,
          9.14000000e+00],
       [  2.72900000e-02,   0.00000000e+00,   7.07000000e+00,
          0.00000000e+00,   4.69000000e-01,   7.18500000e+00,
          6.11000000e+01,   4.96710000e+00,   2.00000000e+00,
          2.42000000e+02,   1.78000000e+01,   3.92830000e+02,
          4.03000000e+00]])

In [10]:
from sklearn import preprocessing

minmax_scale = preprocessing.MinMaxScaler().fit(x_data)
x_scaled_data = minmax_scale.transform(x_data)

x_scaled_data[:3]

array([[  0.00000000e+00,   1.80000000e-01,   6.78152493e-02,
          0.00000000e+00,   3.14814815e-01,   5.77505269e-01,
          6.41606591e-01,   2.69203139e-01,   0.00000000e+00,
          2.08015267e-01,   2.87234043e-01,   1.00000000e+00,
          8.96799117e-02],
       [  2.35922539e-04,   0.00000000e+00,   2.42302053e-01,
          0.00000000e+00,   1.72839506e-01,   5.47997701e-01,
          7.82698249e-01,   3.48961980e-01,   4.34782609e-02,
          1.04961832e-01,   5.53191489e-01,   1.00000000e+00,
          2.04470199e-01],
       [  2.35697744e-04,   0.00000000e+00,   2.42302053e-01,
          0.00000000e+00,   1.72839506e-01,   6.94385898e-01,
          5.99382080e-01,   3.48961980e-01,   4.34782609e-02,
          1.04961832e-01,   5.53191489e-01,   9.89737254e-01,
          6.34657837e-02]])

In [13]:
from sklearn import  linear_model

regr = linear_model.LinearRegression(fit_intercept=True, 
                                     normalize=False, 
                                     copy_X=True, 
                                     n_jobs=8)
regr.fit(x_scaled_data, y_data)
regr

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=8, normalize=False)

In [15]:
regr.coef_
regr.intercept_

array([ 26.61291386])

In [12]:
# # The coefficients
print('Coefficients: ', regr.coef_)
print('intercept: ', regr.intercept_)   

Coefficients:  [[ -9.53495156   4.63952195   0.56906733   2.6885614   -8.64873871
   19.85700309   0.07292809 -16.22877191   7.03006588  -6.46057746
   -8.96255741   3.7248827  -19.04291078]]
intercept:  [ 26.61291386]


In [14]:
regr.predict(x_data[0].reshape(1,-1))

array([[-483.19114376]])

In [18]:
x_data[0].dot(regr.coef_.T) + regr.intercept_

array([-483.19114376])