In [1]:
import pandas as pd
import numpy as np

In [18]:
edges = pd.DataFrame({'source': [0, 1, 2],
                   'target': [2, 2, 3],
                       'weight': [3, 4, 5],
                       'color': ['red', 'blue', 'blue']})

edges

color  source  target  weight
0   red       0       2       3
1  blue       1       2       4
2  blue       2       3       5

In [19]:
edges.dtypes

color     object
source     int64
target     int64
weight     int64
dtype: object

In [20]:
edges["color"]

0     red
1    blue
2    blue
Name: color, dtype: object

In [21]:
pd.get_dummies(edges)

source  target  weight  color_blue  color_red
0       0       2       3           0          1
1       1       2       4           1          0
2       2       3       5           1          0

In [22]:
pd.get_dummies(edges["color"])

blue  red
0     0    1
1     1    0
2     1    0

In [23]:
pd.get_dummies(edges[["color"]])

color_blue  color_red
0           0          1
1           1          0
2           1          0

In [24]:
weight_dict = {3:"M", 4:"L", 5:"XL"}
edges["weight_sign"] = edges["weight"].map(weight_dict)
edges

color  source  target  weight weight_sign
0   red       0       2       3           M
1  blue       1       2       4           L
2  blue       2       3       5          XL

In [26]:
weight_sign = pd.get_dummies(edges["weight_sign"])
weight_sign

L  M  XL
0  0  1   0
1  1  0   0
2  0  0   1

In [30]:
pd.concat([edges, weight_sign], axis=1)

color  source  target  weight weight_sign  L  M  XL
0   red       0       2       3           M  0  1   0
1  blue       1       2       4           L  1  0   0
2  blue       2       3       5          XL  0  0   1

In [35]:
pd.get_dummies(edges).values

array([[0, 2, 3, 0, 1, 0, 1, 0],
       [1, 2, 4, 1, 0, 1, 0, 0],
       [2, 3, 5, 1, 0, 0, 0, 1]])

In [52]:
# Example from - https://chrisalbon.com/python/pandas_binning_data.html

raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['regiment', 'company', 'name', 'preTestScore', 'postTestScore'])
df

regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

In [53]:
bins = [0, 25, 50, 75, 100] # Define bins as 0 to 25, 25 to 50, 60 to 75, 75 to 100
group_names = ['Low', 'Okay', 'Good', 'Great']
categories = pd.cut(df['postTestScore'], bins, labels=group_names)
categories

0       Low
1     Great
2      Good
3      Good
4      Good
5       Low
6     Great
7      Good
8      Good
9      Good
10     Good
11     Good
Name: postTestScore, dtype: category
Categories (4, object): [Low < Okay < Good < Great]

In [54]:
df['categories'] = pd.cut(df['postTestScore'], bins, labels=group_names)
pd.value_counts(df['categories'])

Good     8
Great    2
Low      2
Okay     0
Name: categories, dtype: int64

In [55]:
pd.get_dummies(df)

preTestScore  postTestScore  regiment_Dragoons  regiment_Nighthawks  \
0              4             25                  0                    1   
1             24             94                  0                    1   
2             31             57                  0                    1   
3              2             62                  0                    1   
4              3             70                  1                    0   
5              4             25                  1                    0   
6             24             94                  1                    0   
7             31             57                  1                    0   
8              2             62                  0                    0   
9              3             70                  0                    0   
10             2             62                  0                    0   
11             3             70                  0                    0   

    regiment_Scouts  company_1st  company_2nd  name_Ali  name_Cooze  \
0                 0            1            0         0           0   
1                 0            1            0         0           0   
2                 0            0            1         1           0   
3                 0            0            1         0           0   
4                 0            1            0         0           1   
5                 0            1            0         0           0   
6                 0            0            1         0           0   
7                 0            0            1         0           0   
8                 1            1            0         0           0   
9                 1            1            0         0           0   
10                1            0            1         0           0   
11                1            0            1         1           0   

    name_Jacobson        ...         name_Milner  name_Piger  name_Riani  \
0               0        ...                   0           0           0   
1               1        ...                   0           0           0   
2               0        ...                   0           0           0   
3               0        ...                   1           0           0   
4               0        ...                   0           0           0   
5               0        ...                   0           0           0   
6               0        ...                   0           0           0   
7               0        ...                   0           0           0   
8               0        ...                   0           0           0   
9               0        ...                   0           1           0   
10              0        ...                   0           0           1   
11              0        ...                   0           0           0   

    name_Ryaner  name_Sloan  name_Sone  categories_Low  categories_Okay  \
0             0           0          0               1                0   
1             0           0          0               0                0   
2             0           0          0               0                0   
3             0           0          0               0                0   
4             0           0          0               0                0   
5             0           0          0               1                0   
6             1           0          0               0                0   
7             0           0          1               0                0   
8             0           1          0               0                0   
9             0           0          0               0                0   
10            0           0          0               0                0   
11            0           0          0               0                0   

    categories_Good  categories_Great  
0                 0                 0  
1                 0                 1  
2                 1

### using scikit-learn preprocessing

In [56]:
raw_example = df.as_matrix()
raw_example[:3]

array([['Nighthawks', '1st', 'Miller', 4, 25, 'Low'],
       ['Nighthawks', '1st', 'Jacobson', 24, 94, 'Great'],
       ['Nighthawks', '2nd', 'Ali', 31, 57, 'Good']], dtype=object)

In [57]:
data = raw_example.copy()

In [58]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [59]:
raw_example[:,0]

array(['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons',
       'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts',
       'Scouts'], dtype=object)

In [60]:
le.fit(raw_example[:,0])

LabelEncoder()

In [61]:
le.classes_

array(['Dragoons', 'Nighthawks', 'Scouts'], dtype=object)

In [62]:
le.transform(raw_example[:,0])

array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [63]:
data[:,0] = le.transform(raw_example[:,0])
data[:3]

array([[1, '1st', 'Miller', 4, 25, 'Low'],
       [1, '1st', 'Jacobson', 24, 94, 'Great'],
       [1, '2nd', 'Ali', 31, 57, 'Good']], dtype=object)

In [64]:
label_column = [0,1,2,5]
label_enconder_list = []
for column_index in  label_column:
    le = preprocessing.LabelEncoder()
    le.fit(raw_example[:,column_index])
    data[:,column_index] = le.transform(raw_example[:,column_index])
    label_enconder_list.append(le)
    del le 
data[:3]

array([[1, 0, 4, 4, 25, 2],
       [1, 0, 2, 24, 94, 1],
       [1, 1, 0, 31, 57, 0]], dtype=object)

In [65]:
label_enconder_list[0].transform(raw_example[:10,0])

array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2])

In [66]:
one_hot_enc = preprocessing.OneHotEncoder()
data[:,0].reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2]], dtype=object)

In [68]:
one_hot_enc.fit(data[:,0].reshape(-1,1))

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [70]:
one_hot_enc.n_values_

array([3])

In [74]:
one_hot_enc.active_features_

array([0, 1, 2])

In [75]:
data[:,0].reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2]], dtype=object)

In [76]:
onehotlabels = one_hot_enc.transform(data[:,0].reshape(-1,1)).toarray()
onehotlabels

array([[ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.]])