In [1]:
import numpy as np

In [2]:
test_exmaple = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_exmaple

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
test_exmaple[0][0]

1

In [4]:
test_exmaple[0,0]

1

In [8]:
test_exmaple[0,0] = 10 # Matrix 0,0 에 12 할당
test_exmaple

array([[10,  2,  3],
       [ 4,  5,  6]])

In [9]:
test_exmaple[0][0] = 5 # Matrix 0,0 에 12 할당
test_exmaple[0,0]

5

#### slicing

In [22]:
test_exmaple = np.array([
    [1, 2, 5,8], [1, 2, 5,8],[1, 2, 5,8],[1, 2, 5,8]], int)
test_exmaple[:2,:] 

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [21]:
test_exmaple[:,1:3] 
test_exmaple[1,:2] 

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [13]:
test_exmaple = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_exmaple[:,2:] # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [14]:
test_exmaple[1,1:3] # 1 Row의 1열 ~ 2열

array([7, 8])

In [10]:
test_exmaple[1:3] # 1 Row ~ 2Row의 전체

array([[4, 5, 6]])

In [16]:
a = np.arange(100).reshape(10,10)
a[:, -1].reshape(-1,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])