In [1]:
import pandas as pd

In [2]:
# !wget http://www-stat.wharton.upenn.edu/~waterman/DataSets/uva.txt

In [3]:
data_url= "http://www-stat.wharton.upenn.edu/~waterman/DataSets/uva.txt"
data_url= "./uva.txt"

dataframe = pd.read_table(data_url)

In [4]:
dataframe[:5]

who  Newbie   Age  Gender Household Income Sexual Preference  \
0  id74364       0  54.0    Male           $50-74          Gay male   
1  id84505       0  39.0  Female        Over $100      Heterosexual   
2  id84509       1  49.0  Female           $40-49      Heterosexual   
3  id87028       1  22.0  Female           $40-49      Heterosexual   
4  id76087       0  20.0    Male           $30-39          Bisexual   

      Country Education Attainment Major Occupation Marital Status  \
0     Ontario         Some College         Computer          Other   
1      Sweden         Professional            Other          Other   
2  Washington         Some College       Management          Other   
3     Florida         Some College         Computer        Married   
4  New Jersey         Some College        Education         Single   

  Years on Internet  
0            4-6 yr  
1            1-3 yr  
2        Under 6 mo  
3           6-12 mo  
4            1-3 yr

In [5]:
dataframe.shape

(19583, 11)

In [6]:
dataframe.dtypes

who                      object
Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Country                  object
Education Attainment     object
Major Occupation         object
Marital Status           object
Years on Internet        object
dtype: object

In [7]:
dataframe["Marital Status"].unique()

array(['Other', 'Married', 'Single', 'Divorced', 'Widowed', nan,
       'Separated'], dtype=object)

In [8]:
dataframe.pop('who') # dataframe = dataframe.ix[:, 1:]
dataframe.pop('Country')
dataframe.pop('Years on Internet')

dataframe.dtypes

Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Education Attainment     object
Major Occupation         object
Marital Status           object
dtype: object

In [9]:
dataframe["Gender"] = dataframe["Gender"].astype("category")
dataframe.dtypes

Newbie                     int64
Age                      float64
Gender                  category
Household Income          object
Sexual Preference         object
Education Attainment      object
Major Occupation          object
Marital Status            object
dtype: object

In [10]:
for col in ['Household Income', 'Sexual Preference', 'Education Attainment', 'Major Occupation', "Marital Status"]:
    dataframe[col] = dataframe[col].astype('category')
dataframe.dtypes    

Newbie                     int64
Age                      float64
Gender                  category
Household Income        category
Sexual Preference       category
Education Attainment    category
Major Occupation        category
Marital Status          category
dtype: object

In [11]:
dataframe_modified = pd.get_dummies(dataframe)
dataframe_modified[:5]

Newbie   Age  Gender_Female  Gender_Male  Household Income_$10-19  \
0       0  54.0              0            1                        0   
1       0  39.0              1            0                        0   
2       1  49.0              1            0                        0   
3       1  22.0              1            0                        0   
4       0  20.0              0            1                        0   

   Household Income_$20-29  Household Income_$30-39  Household Income_$40-49  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        1   
3                        0                        0                        1   
4                        0                        1                        0   

   Household Income_$50-74  Household Income_$75-99           ...            \
0                        1                        0           ...             
1                        0                        0           ...             
2                        0                        0           ...             
3                        0                        0           ...             
4                        0                        0           ...             

   Major Occupation_Education  Major Occupation_Management  \
0                           0                            0   
1                           0                            0   
2                           0                            1   
3                           0                            0   
4                           1                            0   

   Major Occupation_Other  Major Occupation_Professional  \
0                       0                              0   
1                       1                              0   
2                       0                              0   
3                       0                              0   
4                       0                              0   

   Marital Status_Divorced  Marital Status_Married  Marital Status_Other  \
0                        0                       0                     1   
1                        0                       0                     1   
2                        0                       0                     1   
3                        0                       1                     0   
4                        0                       0                     0   

   Marital Status_Separated  Marital Status_Single  Marital Status_Widowed  
0                         0                      0                       0  
1                         0                      0                       0  
2                         0                      0                       0  
3                         0                      0                       0  
4                         0                      1                       0  

[5 rows x 38 columns]

In [12]:
dataframe_modified.shape

(19583, 38)

In [13]:
dataframe_modified.isnull().sum()

Newbie                                 0
Age                                  561
Gender_Female                          0
Gender_Male                            0
Household Income_$10-19                0
Household Income_$20-29                0
Household Income_$30-39                0
Household Income_$40-49                0
Household Income_$50-74                0
Household Income_$75-99                0
Household Income_Over $100             0
Household Income_Under $10             0
Sexual Preference_Bisexual             0
Sexual Preference_Gay male             0
Sexual Preference_Heterosexual         0
Sexual Preference_Lesbian              0
Sexual Preference_Transgender          0
Sexual Preference_na                   0
Education Attainment_College           0
Education Attainment_Doctoral          0
Education Attainment_Grammar           0
Education Attainment_High School       0
Education Attainment_Masters           0
Education Attainment_Other             0
Education Attain

In [14]:
dataframe_modified.loc[
    pd.isnull(dataframe_modified['Age']), "Age"] = dataframe_modified['Age'].mean()

In [15]:
dataframe_modified['Age'][pd.isnull(dataframe_modified['Age'])]

Series([], Name: Age, dtype: float64)

In [16]:
dataframe_modified.head()

Newbie   Age  Gender_Female  Gender_Male  Household Income_$10-19  \
0       0  54.0              0            1                        0   
1       0  39.0              1            0                        0   
2       1  49.0              1            0                        0   
3       1  22.0              1            0                        0   
4       0  20.0              0            1                        0   

   Household Income_$20-29  Household Income_$30-39  Household Income_$40-49  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        1   
3                        0                        0                        1   
4                        0                        1                        0   

   Household Income_$50-74  Household Income_$75-99           ...            \
0                        1                        0           ...             
1                        0                        0           ...             
2                        0                        0           ...             
3                        0                        0           ...             
4                        0                        0           ...             

   Major Occupation_Education  Major Occupation_Management  \
0                           0                            0   
1                           0                            0   
2                           0                            1   
3                           0                            0   
4                           1                            0   

   Major Occupation_Other  Major Occupation_Professional  \
0                       0                              0   
1                       1                              0   
2                       0                              0   
3                       0                              0   
4                       0                              0   

   Marital Status_Divorced  Marital Status_Married  Marital Status_Other  \
0                        0                       0                     1   
1                        0                       0                     1   
2                        0                       0                     1   
3                        0                       1                     0   
4                        0                       0                     0   

   Marital Status_Separated  Marital Status_Single  Marital Status_Widowed  
0                         0                      0                       0  
1                         0                      0                       0  
2                         0                      0                       0  
3                         0                      0                       0  
4                         0                      1                       0  

[5 rows x 38 columns]

In [17]:
x_data = dataframe_modified.iloc[:, 1:].as_matrix()
y_data = dataframe_modified.iloc[:, 0].as_matrix().reshape(-1, 1)
y_data.shape, x_data.shape

((19583, 1), (19583, 37))

In [18]:
from sklearn import preprocessing # Min-Max Standardzation

min_max_scaler = preprocessing.MinMaxScaler()
x_data = min_max_scaler.fit_transform(x_data)

In [19]:
import numpy as np 

training_idx = np.random.randint(y_data.shape[0], size=int(y_data.shape[0] * 0.8))
test_idx = np.random.randint(y_data.shape[0], size=int(y_data.shape[0] * 0.2))

x_training, x_test = x_data[training_idx,:], x_data[test_idx,:]
y_training, y_test = y_data[training_idx,:], y_data[test_idx,:]

x_training.shape, x_test.shape

((15666, 37), (3916, 37))

In [20]:
from sklearn import linear_model, datasets

logreg = linear_model.LogisticRegression(fit_intercept=True)
logreg.fit(x_training, y_training.flatten())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [27]:
logreg.predict(x_test[:5])

array([0, 0, 1, 0, 0])

In [29]:
logreg.predict_proba(x_test[:5])

array([[ 0.9081863 ,  0.0918137 ],
       [ 0.94959848,  0.05040152],
       [ 0.34271299,  0.65728701],
       [ 0.68450581,  0.31549419],
       [ 0.66189489,  0.33810511]])

In [34]:
x_test.shape

(3916, 37)

In [35]:
y_test.shape

(3916, 1)

In [39]:
logreg.predict(x_test) == y_test.flatten()

array([ True,  True, False, ...,  True, False,  True], dtype=bool)

In [40]:
sum(logreg.predict(x_test) == y_test.flatten()) / len(y_test)

0.74821246169560773

In [41]:
logreg.predict_proba(x_test)

array([[ 0.9081863 ,  0.0918137 ],
       [ 0.94959848,  0.05040152],
       [ 0.34271299,  0.65728701],
       ..., 
       [ 0.93907648,  0.06092352],
       [ 0.78184817,  0.21815183],
       [ 0.91745719,  0.08254281]])

In [42]:
logreg.decision_function(x_test[:5])

array([-2.29168801, -2.93601795,  0.65122744, -0.77455686, -0.67174996])

In [43]:
logreg.predict(x_test[:5])

array([0, 0, 1, 0, 0])